// src/components/all-components/Sample_React.jsx
import React, { useState } from "react"


export default function Sample_React() {
    const [val, setVal] = useState(0);
    return (
        <div>
            Hi, I'm a react component:
            <button onClick={() => setVal(val - 1)}>-</button>
             {val} 
            <button onClick={() => setVal(val + 1)}>+</button>
            My code is:
            <img src="./sample_react.png"/>
        </div>
    );
}

// src/components/all-components/Sample_Vue.vue
<script lang="ts">
export default {
    data() {
        return {
            val: 0
        }
    }
}
</script>

<template>
    Hi, I'm a vue component:
    <button @click="val--">-</button>
    {{ val }}
    <button @click="val++">+</button>
    My code is:
    <img src="./sample_vue.png" />
</template>
